version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers
        environment:
          BUNDLER_VERSION: 2.1.4 
          RAILS_ENV: test
          
      - image: circleci/mysql:5.6.51
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          - MYSQL_ROOT_HOST: '%'

    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - -v1-dependencies{{ checksum "Gemfile.lock" }}
            - -v1-dependencies
      - run:
          name: Bundlerをinstall
          command: |
            gem update --system
            gem install bundler -v 2.1.4
      - save_cache:
          key: protospace-35547-bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - restore_cache:
          keys:
            - rails-demo-yarn-{{ checksum "yarn.lock" }}
            - rails-demo-yarn-
      - run:
          name: Yarnをinstall
          command: yarn install --cache-folder ~/.cache/yarn
      # - run:
      #     name: Wait for DB
      #     command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m
      # - run:
      #     name: Database setup
      #     command: bin/rails db:create db:schema:load --trace
      - run: bundle exec bin/webpack
      - run:
          name: execute rspec
          command: bundle exec rspec
      - store_test_results:
          path: /tmp/test-results